name: Generate License

on:
  workflow_dispatch:
    inputs:
      owner:
        description: Customer Name
        required: true

      product:
        description: Product Name
        required: true
        default: Sanatan Edition

      licenseKey:
        description: License Key
        required: true

      expiry:
        description: "YYYY-MM-DD অথবা none"
        required: true
        default: none

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore Dependencies
        run: dotnet restore Tools/LicenseGenerator

      - name: Build
        run: dotnet build Tools/LicenseGenerator --configuration Release

      - name: Generate License
        run: |
          dotnet run --project Tools/LicenseGenerator -- \
          "${{ github.event.inputs.owner }}" \
          "${{ github.event.inputs.product }}" \
          "${{ github.event.inputs.licenseKey }}" \
          "${{ github.event.inputs.expiry }}" \
          "./keys/private_key.pem" \
          "./output/LICENSE.xml"

      - name: Upload LICENSE.xml
        uses: actions/upload-artifact@v4
        with:
          name: LICENSE
          path: output/LICENSE.xmlxml
